Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

# Splitting method arguments across multiple lines can result in the containing
# method looking long, but not actually increasing the complexity at all.
MethodLength:
  Enabled: false
