language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.4
  - 2.1.8
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
sudo: false
addons:
  code_climate:
    repo_token: "18995229639977d370a4adf13644223c53baa31b9c7fc302a7ce263aa5bc6dbf"
